version: "3.8"

services:
    db:
        image: ale13/mysql_vuln:v3
        container_name: vuln_db
        stdin_open: true
        tty: true
        expose:
            - 3306
            - 33060
        networks:
            network_0:
                ipv4_address: 193.20.1.3

    app:
        image: ale13/vulnerable-flask:v12
        container_name: vulnerable_server
        links:
            - db
        ports:
            - 8088:5000
        networks:
            network_0:
                ipv4_address: 193.20.1.2
        restart: always
    
    attacker:
        image: ale13/attacker_dsp:v3
        container_name: attacker_dsp
        sysctls:
            - net.ipv4.ip_forward=1
        ports:
            - 7681:7681
        privileged: true
        networks:
            network_0:
                ipv4_address: 193.20.1.4
                
    simulator:
        image: ale13/session-simulator-dsp:latest
        container_name: session_dsp
        links:
            - app
        networks:
            network_0:
                ipv4_address: 193.20.1.5
        restart: always
        

networks:
    network_0:
        ipam:
            config:
                - subnet: 193.20.1.1/24
        
